version: "3.8"

services:
  db:
    image: postgres:16
    container_name: udonapp-postgres
    environment:
      POSTGRES_USER: udon_user
      POSTGRES_PASSWORD: udon_pass
      POSTGRES_DB: udon_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: